name: Test setup and measure coverage

on:
  push:
    branches:
      - main
      - add-test-branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MATLAB R2024a
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2024a

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install additional 3p dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy tensorstore

    - name: Run tests
      uses: matlab-actions/run-tests@v2
      with:
        select-by-folder: 'test'
        code-coverage-cobertura: cobertura.xml

    - name: Upload codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        files: ./target/site/cobertura/coverage.xml
        name: codecov-umbrella.xml